# Generated by Django 3.1.7 on 2022-07-06 01:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donatur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_donatur', models.CharField(max_length=200, null=True)),
                ('alamat_donatur', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('no_telp', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Donatur',
            },
        ),
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Jenis Sarana',
            },
        ),
        migrations.CreateModel(
            name='Penyewa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyewa', models.CharField(max_length=200, null=True)),
                ('alamat_penyewa', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('no_telp', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Penyewa',
            },
        ),
        migrations.CreateModel(
            name='Sarana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi_sarana', models.CharField(max_length=200, null=True)),
                ('stok_sarana', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nama_sarana', models.CharField(max_length=200, null=True)),
                ('token_aktifasi_sarana', models.CharField(blank=True, max_length=300, null=True)),
                ('gambar_sarana', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, size=[400, 500], upload_to='gambar/foto_petani', verbose_name='Foto Sarana (400 x 500 pixel)*)')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='arsip/data_qrcode')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('donatur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.donatur')),
                ('jenis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.jenis')),
            ],
            options={
                'verbose_name_plural': 'Petani',
            },
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_petugas', models.CharField(max_length=200, null=True)),
                ('alamat_petugas', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('no_telp', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data Donatur',
            },
        ),
        migrations.CreateModel(
            name='DetailPenyewa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tanggal_pinjam', models.DateField(null=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('penyewa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.penyewa')),
                ('sarana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.sarana')),
            ],
            options={
                'verbose_name_plural': 'Data Detail Penyewa',
            },
        ),
    ]
