# Generated by Django 3.1.7 on 2022-07-17 06:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petugas',
            options={'verbose_name_plural': 'Data Petugas'},
        ),
        migrations.AlterModelOptions(
            name='sarana',
            options={'verbose_name_plural': 'Data Sarana'},
        ),
        migrations.RenameField(
            model_name='petugas',
            old_name='alamat_petugas',
            new_name='alamat',
        ),
        migrations.RenameField(
            model_name='petugas',
            old_name='nama_petugas',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='petugas',
            name='no_telp',
        ),
        migrations.AddField(
            model_name='petugas',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='petugas',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='petugas',
            name='wa',
            field=models.CharField(max_length=200, null=True, verbose_name='No Whatsapp'),
        ),
        migrations.AddField(
            model_name='sarana',
            name='keterangan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sarana',
            name='status',
            field=models.CharField(blank=True, choices=[('BAIK', 'BAIK'), ('KURANG BAIK', 'KURANG BANK'), ('RUSAK', 'RUSAK')], max_length=200, null=True),
        ),
    ]
