# Generated by Django 3.1.7 on 2022-07-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20220717_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpenyewa',
            name='penyewa',
        ),
        migrations.RemoveField(
            model_name='detailpenyewa',
            name='tanggal_kembali',
        ),
        migrations.RemoveField(
            model_name='detailpenyewa',
            name='tanggal_pinjam',
        ),
        migrations.AddField(
            model_name='detailpenyewa',
            name='id_transaksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaksi', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_pinjam', models.DateField(null=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, choices=[('Terpinjam', 'Terpinjam'), ('Kembali', 'Kembali')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('penyewa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.penyewa')),
                ('petugas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.petugas')),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
            },
        ),
        migrations.CreateModel(
            name='TempPenyewa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaksi', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sarana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.sarana')),
            ],
            options={
                'verbose_name_plural': 'Temp Detail Penyewa',
            },
        ),
    ]
